### ISSUE TITLE
SSOFT: todo list

### ISSUE THREAD

**Issue by JulienPeloton** [astrolabsoftware/fink-science#428]
- [x] Add test for the Spark UDF
- [x] rename `model` into `flavor` for better compatibility
- [x] externalise COLUMN definition in fink_utils
- [x] parametrize Nterms
- [ ] ...
